apiVersion: apps/v1
kind: Deployment
metadata:
  name: collect-api-deployment
  labels:
    app: collect-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: collect-api
  template:
    metadata:
      labels:
        app: collect-api
    spec:
      containers:
      - name: collect-api
        image: eu.gcr.io/hypnotic-epoch-235613/twitter-collect:1.0-1d7962e
        ports:
        - containerPort: 9000
        env:
        - name: PLAY_SECRET
          valueFrom:
            secretKeyRef:
              name: collect-api-secrets
              key: PLAY_SECRET
